version: '3.3'

services:
  db:
    image: mariadb:10.3
    restart: always
    volumes:
      - /docker/weatherstation/data:/var/lib/mysql
    command: --max_allowed_packet=32505856 '--wait_timeout=28800'
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: master_data_base
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  datahandler:
    image: jerey/weatherstation-datahandler:latest
    restart: always
    depends_on:
      - db
    environment:  
      DB_HOST: db
    restart: on-failure
    
  weatherstation_server:
    image: jerey/weatherstation-server:latest
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db

  mosquitto:
    image: eclipse-mosquitto:1.6
    restart: always 
    container_name: mosquitto
    network_mode: host
    ports:
      - "1883:1883"
      - "9001:9001"
